# Generated by Django 3.2.6 on 2021-08-26 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address1',
            new_name='address_line1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address2',
            new_name='address_line2',
        ),
    ]
