# Generated by Django 3.2.6 on 2021-09-01 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        ('Orders', '0004_rename_city_order_town_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address_line2',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=11111, on_delete=django.db.models.deletion.CASCADE, to='User.address'),
            preserve_default=False,
        ),
    ]
